import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { fetchFilm } from '../api';
import styles from '../styles/Home.module.css';

export default function Home() {
	// const { data } = useQuery({
	// 	queryKey: ['films', 'tv', 10],
	// 	queryFn: fetchFilm,
	// 	keepPreviousData: true
	// });

	// data && console.log(data.results);

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1>React Query Utilizations with NextJS</h1>
				<br />
				<Link href={`/movie/popular/${1}`}>
					<h1 style={{ cursor: 'pointer' }}>Popular movie</h1>
				</Link>
				<Link href={`/tv/popular/${1}`}>
					<h1 style={{ cursor: 'pointer' }}>Popular TV</h1>
				</Link>
			</main>
		</div>
	);
}
